[package]
name = "lru"
version = "0.1.0"
authors = ["Jack Drogon <jack.xsuperman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru = "0.1.17"

[[bin]]
name = "lru"
path = "lru.rs"
