[package]
name = "mio-sample"
version = "0.1.0"
authors = ["Jack Drogon <jack.xsuperman@gmail.com>"]
features = ["os-poll", "net"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.7", features = ["os-poll", "net"]}

[[bin]]
name = "tcp_server"
path = "src/tcp_server.rs"
